version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      #      - run: apk add --no-cache bash curl git openssh-client
      - checkout
      - run:
          name: Generate python version cache key
          command: python3 --version > PY_VERSION
      - restore_cache:
          key:  v1-{{ checksum "PY_VERSION" }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements/test.txt" }}
          paths:
            - "venv"
      - run:
          name: Install pip packages
          command: |
            python3 -m venv venv
            venv/bin/pip install --upgrade -r requirements/test.txt
      - save_cache:
          key:  v1-{{ checksum "PY_VERSION" }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements/test.txt" }}
          paths:
            - "venv"
      - run:
          name: pip freeze
          command: venv/bin/pip freeze
      - run:
          name: flake8
          command: venv/bin/flake8 pyticketswitch
      - run:
          name: pylint
          command: venv/bin/py.test
      - run:
          name: behave
          command: venv/bin/behave
      - run: go test -v -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic ./...
        #     - run:
        #          name: Report code coverage
        #          command: |
        #            bash <(curl -s https://codecov.io/bash) -t 58cee431-7146-4cd2-acc7-943a61b19dc4

workflows:
  version: 2
  test:
    jobs:
      - test

