version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      #      - run: apk add --no-cache bash curl git openssh-client
      - checkout
      - run:
          name: Generate python version cache key
          command: python3 --version > PY_VERSION
      - restore_cache:
          key:  v3-{{ checksum "PY_VERSION" }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements/test.txt" }}
          paths:
            - "venv"
      - run:
          name: Install pip packages
          command: |
            python3 -m venv venv
            venv/bin/pip install --upgrade -r requirements/test.txt
      - save_cache:
          key:  v3-{{ checksum "PY_VERSION" }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements/test.txt" }}
          paths:
            - "venv"
      - run:
          name: pip freeze
          command: venv/bin/pip freeze
      - run:
          name: flake8
          command: venv/bin/flake8 pyticketswitch
      - run:
          name: pytest
          command: venv/bin/py.test
      - run:
          name: behave
          command: venv/bin/behave
      - run:
          name: coverage
          command: venv/bin/coverage run -m pytest
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: reports/
      - run:
          name: Report Python code coverage
          command: |
            . venv/bin/activate
            coverage combine
            codecov -t ca9be7f8-5c8c-4cd7-962d-b189e2d0a436

workflows:
  version: 2
  test:
    jobs:
      - test

